### PR TITLE
update docker repository

### PR DESCRIPTION
**Pull request by chasebolt**
- switching to the new docker repo. edge is now disabled by default. support for oracle, amazon, and centos 6 no longer exist from docker.
- switch to dokken for test-kitchen

### CODE REVIEW

**Comment by tas50** [comment]
Can we retain the vagrant based kitchen config for standard testing

**Comment by chasebolt** [comment]
sure

**Comment by chasebolt** [comment]
travis is going to fail until https://github.com/someara/dokken-images/pull/8 is merged in

**Comment by chasebolt** [comment]
fixes #5

**Pull request merged**
